all:
  children:
    nginx:
      hosts:
        nginx-dev:
          ansible_host: "{{ nginx_hosts.dev.ip }}"
        nginx-prod:
          ansible_host: "{{ nginx_hosts.prod.ip }}"
  vars:
    ansible_port: "{{ ssh_port | default(target_ssh_port) }}"
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
